export const commandList: Record<string, { class: string, tag: string, content?: boolean | string, blockTag?: string }> = {
	"大見出し": { class: "o-midashi", tag: "h3" },
	"中見出し": { class: "naka-midashi", tag: "h4" },
	"小見出し": { class: "ko-midashi", tag: "h5" },
	"同行大見出し": { class: "dogyo-o-midashi", tag: "h3" },
	"同行中見出し": { class: "dogyo-naka-midashi", tag: "h4" },
	"同行小見出し": { class: "dogyo-ko-midashi", tag: "h5" },
	"窓大見出し": { class: "mado-o-midashi", tag: "h3" },
	"窓中見出し": { class: "mado-naka-midashi", tag: "h4" },
	"窓小見出し": { class: "mado-ko-midashi", tag: "h5" },
	"縦中横": { class: "tatechuyoko", tag: "span" },
	"傍点": { class: "sesame_dot", tag: "em" },
	"白ゴマ傍点": { class: "white_sesame_dot", tag: "em" },
	"丸傍点": { class: "black_circle", tag: "em" },
	"黒三角傍点": { class: "black_up-pointing_triangle", tag: "em" },
	"白三角傍点": { class: "white_up-pointing_triangle", tag: "em" },
	"二重丸傍点": { class: "bullseye", tag: "em" },
	"蛇の目傍点": { class: "fisheye", tag: "em" },
	"ばつ傍点": { class: "saltire", tag: "em" },
	"左に傍点": { class: "sesame_dot_after", tag: "em" },
	"左に白ゴマ傍点": { class: "white_sesame_dot_after", tag: "em" },
	"左に丸傍点": { class: "black_circle_after", tag: "em" },
	"左に黒三角傍点": { class: "black_up-pointing_triangle_after", tag: "em" },
	"左に白三角傍点": { class: "white_up-pointing_triangle_after", tag: "em" },
	"左に二重丸傍点": { class: "bullseye_after", tag: "em" },
	"左に蛇の目傍点": { class: "fisheye_after", tag: "em" },
	"左にばつ傍点": { class: "saltire_after", tag: "em" },
	"傍線": { class: "underline_solid", tag: "em" },
	"二重傍線": { class: "underline_double", tag: "em" },
	"鎖線": { class: "underline_dotted", tag: "em" },
	"破線": { class: "underline_dashed", tag: "em" },
	"波線": { class: "underline_wave", tag: "em" },
	"左に傍線": { class: "overline_solid", tag: "em" },
	"左に二重傍線": { class: "overline_double", tag: "em" },
	"左に鎖線": { class: "overline_dotted", tag: "em" },
	"左に破線": { class: "overline_dashed", tag: "em" },
	"左に波線": { class: "overline_wave", tag: "em" },
	"太字": { class: "futoji", tag: "span" },
	"斜体": { class: "shatai", tag: "span" },
	"キャプション": { class: "caption", tag: "span" },
	"改丁": { class: "notes kaicho", tag: "span", content: true },
	"改ページ": { class: "notes new-page", tag: "span", content: true },
	"改見開き": { class: "notes new-mihiraki", tag: "span", content: true },
	"改段": { class: "notes new-block", tag: "span", content: true },
	"地付き": { class: "chitsuki", tag: "div" },
	"ページの左右中央": { class: "chuou", tag: "div" },
	"左にルビ付き": { class: "ruby-under", tag: "ruby" },
	"注記付き": { class: "ruby notes", tag: "ruby" },
	"左に注記付き": { class: "ruby-under", tag: "ruby" },
	"割り注": { class: "warichu", tag: "span" },
	"改行": { class: "notes", tag: "span", content: "<br />" },
	"行右小書き": { class: "superscript", tag: "sup" },
	"行左小書き": { class: "superscript", tag: "sub" },
	"上付き小文字": { class: "superscript", tag: "sub" },
	"下付き小文字": { class: "superscript", tag: "sub" },
	"罫囲み": { class: "keigakomi", blockTag: "div", tag: "span" },
	"横組み": { class: "yokogumi", blockTag: "div", tag: "span" },
	"大きな文字": { class: "dai", blockTag: "div", tag: "span" },
	"小さな文字": { class: "sho", blockTag: "div", tag: "span" },
	"前書き": { class: "foreword", tag: "div" },
	"後書き": { class: "afterword", tag: "div" },
}